### ISSUE TITLE
Allow multiple level error code

### ISSUE THREAD

**Issue by doubleface** [konnectors/libs#114]
Here is the need : have categories of errors. Collect has predefined locales for categories and may have locale for more detailed messages inside categories or not.

Here is the API

```javascript
const {log} = require('cozy-konnector-libs')
log('error', ['LOGIN_FAILED', 'CAPTCHA'])
```

Will result with `LOGIN_FAILED-CAPTCHA` error code ("-" will be forbidden)

If collect knows the `LOGIN_FAILED` code but not `LOGIN-FAILED-CAPTCHA`, it will display the locale associated with `LOGIN_FAILED`.

**Comment by ptbrowne** [comment]
I would use the dot instead of the dash. "LOGIN_FAILED.CAPTCHA" indicates better that one is the child of the other.
