### ISSUE TITLE
Use `lerna-changelog`

### ISSUE THREAD

**Issue by CPatchane** [konnectors/libs#150]
It could be great to have a changelog to these packages. I use [`lerna-changelog`](https://github.com/lerna/lerna-changelog) with [`create-cozy-app`](https://github.com/CPatchane/create-cozy-app) and it's pretty cool and quick to generate a changelog text.
Just a proposal :)

**Comment by doubleface** [comment]
Done 7b16379d640b2aa8ade0535a0c8b1d0e56aa8fb4
