### ISSUE TITLE
Feedback after first contribution

### ISSUE THREAD

**Issue by y-lohse** [konnectors/libs#237]
Here's a bit of feedback after writting my first konnector in a long time:

1. The start of [the tutorial](https://docs.cozy.io/en/dev/konnector/) is great, but after `Typical workflow` I had no idea where to continue. The rest of the documentation is more about late-stage stuff. Maybe we should tell people to go to the `index.js` file after that?
1. The `konnector-dev-config.json` file is not valid JSON — it's missing quotes around `login` and `password` field names
1. By default, downloaded files go to the root of the project. I filled out `folder_path` in `konnector-dev-config.json` to create them in a subfolder in `standalone` mode, but then in `dev` mode it's still using `folder_path`, so it tried to create them on the cozy at the path `/./fixtures/`, which obviously doesn't work. `folder_path` should probably not be taken into account when using `dev` mode?
1. For the `dev` tests, I used a cozy created with the docker image, and my konnector failed because the database `io.cozy.bank.accounts`didn't exist.
1. I tried to understand how the `scrape` function works, but it's documentation is not very helpful
1. `cheerio` (and `jquery`) have this annoying behavior where [`.each`](https://github.com/y-lohse/cozy-konnector-esstrasbourg-electricite/blob/master/src/index.js#L64) will return an unextended element, so if you want to manipulate it you need to extend it again, so you need cheerio. I've added a dependency to [`cheerio`](https://github.com/y-lohse/cozy-konnector-esstrasbourg-electricite/blob/master/src/index.js#L8) but since it's already a dependency of `cozy-konnector-libs`, it would be cool to just export it from there

That's it, hope it helps!

**Comment by enguerran** [comment]
Here is todo list:

- [ ] enhance tutorial located here https://docs.cozy.io/en/dev/konnector/
- [ ] update `konnector-dev-config.json` generation to be valid json
- [ ] stub `cozy-client-js` to download files in another folder than root
- [ ] ~~`io.cozy.bank.accounts` do not exist on empty `cozy-stack`~~ [won't fix]
- [ ] enhance documentation of `scrape()` function
- [ ] enable cheerio export

I addressed the `1.` in https://github.com/cozy/cozy.github.io/pull/69

The `4.` won't be fix within this issue. Please open an issue at cozy/cozy-banks or cozy/cozy-stack.

**Comment by doubleface** [comment]
https://github.com/konnectors/libs/pull/273 addresses the 3 by save the files in `/cozy-konnector-dev-root` path by default in dev mode

**Comment by enguerran** [comment]
I don't know what to do for the last point (`6.`).

**Comment by doubleface** [comment]
@y-lohse @enguerran I don't fully understend the need either. @y-lohse Can you give an example?

**Comment by y-lohse** [comment]
Yeah sure.

```
const data = {}
const $trs = $('#mytable tr')
$trs.each(tr => {
  data.lol = tr.find('td.lol').text()
})
```

This code will fail, because `$.each` returns a plain, non-extended element. So you can't `.find` on it or any other convenient things. I do'nt know about you, but this happens to me all the time, even back with jquery.

So what you do is:

```
const data = {}
const $trs = $('#mytable tr')
$trs.each(tr => {
  const $tr = cheerio(tr)
  data.lol = $tr.find('td.lol').text()
})
```

But now we need to `require` cheerio. Right now I have 2 choices to do that:

- just `require` it — that will work because it's a dependency of `cozy-konnector-libs`, but it's not recomended
- add `cheerio` to my own dependencies

A third option would be that `cozy-konnector-libs` exports `cheerio`, so that I can `require` it along with `BaseKonnector`, `requestFactory`, etc. I think this is in line with what `cozy-konnector-libs` already does.

Does that help?

**Comment by enguerran** [comment]
If you need `cheerio` outside `konnectos/libs`, there is no problem to `require("cheerio")`, no need to add it to you own dependencies.

**Comment by y-lohse** [comment]
…until `konnector-libs` switches away from cheerio and my connector breaks :p

If a connector needs a standalone version of `cheerio`, it should either be explicitly provided by `cozy-konnector-libs`, or added to the dependencies. Hoping that some other package provides cheerio is not very safe.

That being said it's a minor point, and "just add cheerio as a dependency" is a valid answer as well.

**Comment by y-lohse** [comment]
That's the current option, which again, is fine too.

But I also need `request` for example, and I'm getting that through `cozy-konnector-libs`. Same for the utility logger.

But let's forget about that one, we'll see if it comes up again. Since the rest is done, I think we can close this issue!

**Comment by ptbrowne** [comment]
Alright, let's close. For the record I think it's better if we do not import other dependencies through our library. IMHO we should play nice with other libraries, be composable and have a strong limit on what we do and what we don't. People should not be afraid of importing the libraries they need. By hiding imports, I feel like it's harder to understand what the library is standing for, and it puts a higher dependency on us and a bigger API surface.

**Comment by doubleface** [comment]
Actually, I don't see a problem with adding cheerio explicitly as a dependency when you require it.

And yes, this api of cheerio/jquery sucks and the scrape function is a good way to hide it
