### ISSUE TITLE
Rename signin to make it more discoverable

### ISSUE THREAD

**Issue by laedit** [konnectors/libs#290]
I am developing a new [konnector](https://github.com/laedit/cozy-konnector-gazdestrasbourg) for [Gaz de Strasbourg](https://agence-en-ligne.es-gazdestrasbourg.fr/) and since it is heavily based on old ASP.NET form navigation, I use `signin` to submit the form for each navigation.

In order to help everyone realize that `signin` isn't just for authentication, I think that it should be renamed like `submitForm`, or at least exposed under two names.

I can propose a PR if you are ok with the idea.

**Comment by doubleface** [comment]
I like the second solution with two names. submitForm is OK for me.

I think you can do your PR, thanks :+1: !
