### ISSUE TITLE
Printing a cheerio object runs infinitely

### ISSUE THREAD

**Issue by sebn** [konnectors/libs#299]
Actually not a cheerio issue.
I believe the offending line is [here](https://github.com/konnectors/libs/blob/ea51cfbcb0d55f028368b9315f2368c21b895d83/packages/cozy-logger/src/log-formats.js#L5).

**Workaround**:

```js
const util = require('util')
util.inspect.defaultOptions.depth = 2
```

**Comment by sebn** [comment]
cc @doubleface

**Comment by doubleface** [comment]
Of course! Thanks @sebn !
