### ISSUE TITLE
Docs for API is full of duplicate and messy

### ISSUE THREAD

**Issue by ko-dever** [konnectors/libs#388]
Hello.

[The documentation for API](https://github.com/konnectors/libs/blob/master/packages/cozy-konnector-libs/docs/api.md) is quite messy and full of duplicate (every definition, example and snippets can be found twice in the document, the snippets are in raw text and coloured, ...).

Is this intentional ?

I was about to clean and rearrange the document, but maybe it is auto-generated or whatever.

**Comment by clochix** [comment]
Hello @ko-dever,

Thanks for reporting. I guess some part of this documentation may be auto-generated so I'm pinging the developer.

**Comment by ptbrowne** [comment]
I think it's better now that #389 is merged. Do you confirm @ko-dever  ? Thanks for reporting the issue 👍

**Comment by ptbrowne** [comment]
I think it is added to things that are exported. I am not really sure as it
is JSDoc that adds this :/ Cool that you find it better, docs is always
hard to priorize against other things, but do not  hesitate if you have any
suggestions.

Closing this :)
