### ISSUE TITLE
Allow users to use cozy-client

### ISSUE THREAD

**Issue by cedricmessiant** [konnectors/libs#415]
As a first step towards a complete migration to `cozy-client`, it would be nice to make `cozy-client` available to new konnectors. For example, we chose to use `cozy-client` in the new version of the Google konnector. 

The code we use to initialize the client is gathered in this file: https://github.com/konnectors/cozy-konnector-google/blob/master/src/CozyUtils.js so we will be able to quickly move it in `cozy-konnector-libs`

**Comment by doubleface** [comment]
Fixed by #533
