### ISSUE TITLE
Ability to specify additional doctypes for cozy-konnector-dev

### ISSUE THREAD

**Issue by ptbrowne** [konnectors/libs#55]
When using `cozy-konnector-dev` to run services (bank notifications), we need to add the `io.cozy.accounts` into our manifest.webapp since `cozy-konnector-dev` creates an account. See doc here : https://gitlab.cozycloud.cc/labs/cozy-bank/blob/master/docs/dev.md#notifications

It could be useful to be able to specify `--doctypes io.cozy.accounts` and it would add the doctypes to the list of doctypes for which it creates a token. What do you think @doubleface ?

Additionally, since those tools can be used to run services, I thought of the name "task" to regroup konnector and services, and possibly workers, what do you think about renaming the binaries into `cozy-task-*` ?

**Comment by doubleface** [comment]
About `cozy-task-*`, my advice is that the cli part should not be in `cozy-konnector-libs`. It would be better to create a new npm package for that (cozy-worker seems to be ok for that, cozy-task would be too vague in my opinion). And this package could be installed globally as bonus.

**Comment by doubleface** [comment]
@ptbrowne About the permission thing, I think cozy-konnector-dev can add the io.cozy.accounts permission itself and then the --doctypes option would no be needed. Would it be ok for you ?

**Comment by doubleface** [comment]
@ptbrowne https://github.com/cozy/cozy-konnector-libs/pull/57

**Comment by ptbrowne** [comment]
> About cozy-task-*, my advice is that the cli part should not be in cozy-konnector-libs. 

I agree. For the naming, I asked the stack what name did they use for konnector and services and they use the worker "exec". I like cozy-exec because it reads as a verb.

```
cozy-exec node notifications.js
```

seems clearer than 

```
cozy-worker node notifications.js
```

IMHO

> . Would it be ok for you ?

I just had the case where I needed to add both io.cozy.accounts and io.cozy.notifications permissions so no it would not be sufficient for me.

**Comment by ptbrowne** [comment]
You're right.

**Comment by doubleface** [comment]
I think we can close this issue with https://github.com/konnectors/libs/pull/57 and since we have cozy-jobs-cli now.
