### ISSUE TITLE
timeout options for waitForTwoFACode should be a real timeout

### ISSUE THREAD

**Issue by gregorylegarec** [konnectors/libs#571]
As we worked on Dummy TwoFA konnector with @y-lohse, we realized that the `timeout` option in function `waitForTwoFaCode` was not a real `timeout` but a kind of `endTime` instead : it's expecting a dateTime in the future, not a given amount of seconds to wait.

**Comment by doubleface** [comment]
I agree this was a bad choice indeed. Let's add an endTime alias for this option and mark the timeout option as deprecated. I have the same issue for the saveFiles function from cozy-konnector-libs
