### ISSUE TITLE
Since linkBankOperations does not works in saveBills

### ISSUE THREAD

**Issue by doubleface** [konnectors/libs#69]
In https://github.com/cozy/cozy-konnector-libs/blob/master/libs/saveBills.js#L41 , originalEntries do not have an _id attribute and then the operation link does not work and gives "bill has no id, impossible to add it to an operation" for the matching operations.

**Comment by ptbrowne** [comment]
I have made the assumption that the entries we get in linkBill should be the same objects as in `originalEntries`, maybe we lose the reference in https://github.com/cozy/cozy-konnector-libs/blob/master/libs/addData.js#L13. One possible solution would be to `.then(() => return entry)` there to keep the original entry object. Can you try ?
